# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go_cicd_job:
    name: Go CICD Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Golang CI code Lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ./
      
    - name: Run Go Build
      run: go build -v ./...
      
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2

    - name: Setup docker
      uses: docker/setup-buildx-action@v2.7.0
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Docker Build and Push
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/linktoqr:latest

# TODO: Tests 
