# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Link-to-QR AWS CD  

on:
  workflow_call:

jobs: 
  go_aws_cd_job:
    name: CD in AWS

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tf code in runner environment
      uses: actions/checkout@v3.5.2

    # Configure Terraform cloud API token, since we are using Remote backend option of Terraform cloud in AWS code
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Add the AWS Creds as ENV variable in TF Cloud workspace, since the tf run happens in TF Cloud environment

    # Call rest of the Terraform commands
    - name: Terraform init and validate
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init
          
        echo "** Running Terraform Validate**"
        terraform validate
      working-directory: create_infra/ec2
    - name: Terraform plan and apply
      run: |
        echo `pwd`   
        echo "** Running Terraform Plan**"
        terraform plan
          
        echo "** Running Terraform Apply**"
        terraform apply -auto-approve
      working-directory: create_infra/ec2
  
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform destroy -auto-approve
      working-directory: create_infra/ec2