# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Link-to-QR Kubernetes CD  

on:
  workflow_call:

jobs: 
  go_k8s_cd_job:
    name: CD in Kubernetes
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0
    
    - name: Install Minikube for GitHub Actions
      uses: medyagh/setup-minikube@v0.0.13
      
    - name: Install Kubectl tool for GitHub Actions
      uses: Azure/setup-kubectl@v3

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init and velidate and plan
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Validate**"
        terraform validate
        
        echo "** Running Terraform Plan**"
        terraform plan
      working-directory: create_infra/kubernetes

    - name: Terraform Apply
      run: |
        echo "** Running Terraform Apply**"
        terraform apply -auto-approve
      working-directory: create_infra/kubernetes

    - name: Verify Kubernetes Deployment
      run: |
        echo "** kubectl get deployment **"
        kubectl get deployment -n ns_linktoqr 
        
    - name: Expose Kubernetes Deployment
      run: |
        echo "** kubectl expose deployment **"
        kubectl expose deployment linktoqr --port=80 --target-port=8000 -n ns_linktoqr
        sleep 10
        kubectl get service -n ns_linktoqr -o wide
  
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform plan -destroy
      working-directory: create_infra/kubernetes
